### PR TITLE
i18n: Add Kazakh

### PR DESCRIPTION
**Pull request by Fontan030**
The original Silkscreen-Regular font included only Latin characters, so I modified it with FontForge to add Cyrillic letters. Then I built the app; overall works fine on my phone, but I don't know what to do with the Atkinson Hyperlegible font that doesn't have Cyrillic too (and it would be much harder for me to adapt a non-pixelated font).
After enabling Atkinson Hyperlegible in Settings, the system substitutes all non-Latin characters with some built-in font; that would look fine with Russian alphabet (consisting of 33 letters), while the Kazakh alphabet has 9 extra letters which get messed up
Screenshot_20231107-014505
Screenshot_20231107-014511
Screenshot_20231107-014617

### CODE REVIEW

**Comment by Fontan030** [comment]
I've managed to make a good-looking Cyrillic version of the Hyperlegible font, so now the translation can be merged without any issues
Screenshot_20231124-053054

**Comment by adil192** [comment]
This is really cool, please can you edit the font licenses as well?

**Comment by Fontan030** [comment]
Should I just add a new line to OFL.txt (something like `Copyright 2023 Fontan030 <myemail>`) or is there a strict requirement to [rename](https://lwn.net/Articles/552178/) all the fonts and change their metadata?

**Comment by Fontan030** [comment]
After reading some of the other Google Fonts licenses I figured out that reserved font names are usually specified after the copyright statement (like [here](https://raw.githubusercontent.com/google/fonts/main/ofl/akatab/OFL.txt) or [here](https://raw.githubusercontent.com/google/fonts/main/ofl/durusans/OFL.txt)). Neither Silkscreen nor Atkinson Hyperlegible has RFN clause in OFL.txt, so appending one line to them should be acceptable

**Comment by adil192** [comment]
That seems correct according to the [OFL Q&A 3.1](https://scripts.sil.org/cms/scripts/page.php?item_id=OFL-FAQ_web#a46b6e7d)

**Review by adil192 — APPROVED** [review]

**Comment by adil192** [comment]
Thanks!

**Comment by adil192** [comment]
Hey @Fontan030, hope you're well. If you're able to, it would be amazing if you could translate the new strings in the `kk` section of [_missing_translations.yaml](https://github.com/adil192/ricochlime/blob/main/lib/i18n/_missing_translations.yaml) (of course, no worries if not)

**Pull request merged**
